### ISSUE TITLE
Please fix the "Usage" example in your README.rst

### ISSUE THREAD

**Issue by sebma** [learningequality/python-ifcfg#8]
Hi,

When I type `for interface in ifcfg.interfaces:`, python says : 

`TypeError: 'function' object is not iterable`

and if I type `for interface in ifcfg.interfaces():`, then it says : 

`TypeError: string indices must be integers`

Can you please fix the "Usage" example in your `README.rst` ?

**Comment by benjaoming** [comment]
Thanks for the report @sebma :)

You might be familiar with the person who posted this issue? :) https://github.com/ftao/python-ifcfg/issues/12

**Comment by sebma** [comment]
No, not at all. It's a coincidence :)

The [PYPI page for ifcfg](https://pypi.python.org/pypi/ifcfg/) points to your github repo.

Is not your repo. the original one for the ifcfg python module ?

**Comment by benjaoming** [comment]
I try to get things to @ftao because that's where things have been maintained, then I push it to PyPI -- it's nice that maintainers can share responsibility in some cases.. I think none of us are super passionate about it, just want it to work :)

Odd that you have reported this within hours of the other issue!! What a coincidence!! :)
